import imageProduct1 from '../../assets/images/backgroud.png';

export const Products = [
    {
        id: 1,
        name: "Trà Xanh Tân Cương",
        price: 120000,
        old_price: 150000,
        discount: "Giảm 20%",
        rating: "★★★★★ (95+ đánh giá)",
        weight: "200g",
        packaging: "Hộp thiếc sang trọng",
        origin: "Thái Nguyên",
        image: imageProduct1,
        description:
            "Trà xanh Tân Cương nổi bật với vị chát nhẹ, hậu ngọt sâu, được thu hái thủ công từ vùng chè Thái Nguyên.",
        slug: "tra-xanh-tan-cuong",
    },
    {
        id: 2,
        name: "Trà Shan Tuyết Cổ Thụ",
        price: 150000,
        old_price: 180000,
        discount: "Giảm 17%",
        rating: "★★★★★ (110+ đánh giá)",
        weight: "250g",
        packaging: "Túi giấy kraft cao cấp",
        origin: "Hà Giang",
        image: imageProduct1,
        description:
            "Trà Shan Tuyết được hái từ cây chè cổ thụ hàng trăm năm tuổi, mang hương vị đậm đà và tinh khiết.",
        slug: "tra-shan-tuyet-co-thu",
    },
    {
        id: 3,
        name: "Trà Oolong Nhẹ",
        price: 180000,
        old_price: 210000,
        discount: "Giảm 15%",
        rating: "★★★★☆ (80+ đánh giá)",
        weight: "300g",
        packaging: "Hũ thủy tinh kín khí",
        origin: "Lâm Đồng",
        image: imageProduct1,
        description:
            "Trà Oolong lên men nhẹ, vị dịu, thơm hoa, giúp thư giãn tinh thần và hỗ trợ tiêu hóa.",
        slug: "tra-oolong-nhe",
    },
    {
        id: 4,
        name: "Trà Đen Hảo Hạng",
        price: 100000,
        old_price: 125000,
        discount: "Giảm 20%",
        rating: "★★★★☆ (60+ đánh giá)",
        weight: "250g",
        packaging: "Túi nhôm bạc giữ hương",
        origin: "Bảo Lộc",
        image: imageProduct1,
        description:
            "Trà đen đậm vị, màu nước đỏ sậm, thích hợp dùng vào buổi sáng hoặc pha trà sữa.",
        slug: "tra-den-hao-hang",
    },
    {
        id: 5,
        name: "Trà Sen Tây Hồ",
        price: 220000,
        old_price: 260000,
        discount: "Giảm 15%",
        rating: "★★★★★ (70+ đánh giá)",
        weight: "100g",
        packaging: "Hộp gỗ khắc hoa sen",
        origin: "Hà Nội",
        image: imageProduct1,
        description:
            "Trà ướp sen Tây Hồ truyền thống với mùi thơm quyến rũ, ngọt thanh, thích hợp làm quà biếu.",
        slug: "tra-sen-tay-ho",
    },
    {
        id: 6,
        name: "Trà Nhài Tự Nhiên",
        price: 95000,
        old_price: 110000,
        discount: "Giảm 14%",
        rating: "★★★★☆ (55+ đánh giá)",
        weight: "150g",
        packaging: "Túi zip khóa kéo",
        origin: "Bắc Giang",
        image: imageProduct1,
        description:
            "Trà nhài hương dịu nhẹ, kết hợp giữa trà xanh và hoa nhài ướp thủ công truyền thống.",
        slug: "tra-nhai-tu-nhien",
    },
    {
        id: 7,
        name: "Trà Gạo Lứt Rang",
        price: 70000,
        old_price: 85000,
        discount: "Giảm 18%",
        rating: "★★★☆☆ (40+ đánh giá)",
        weight: "300g",
        packaging: "Túi giấy có khóa kéo",
        origin: "Đồng Tháp",
        image: imageProduct1,
        description:
            "Trà từ gạo lứt rang thơm tự nhiên, không caffeine, tốt cho sức khỏe và hỗ trợ tiêu hóa.",
        slug: "tra-gao-lut-rang",
    },
    {
        id: 8,
        name: "Trà Gừng Mật Ong",
        price: 110000,
        old_price: 135000,
        discount: "Giảm 19%",
        rating: "★★★★★ (90+ đánh giá)",
        weight: "200g",
        packaging: "Túi zip bạc 2 lớp",
        origin: "Đà Lạt",
        image: imageProduct1,
        description:
            "Sự kết hợp giữa gừng cay và mật ong ngọt dịu, giúp tăng cường miễn dịch và giữ ấm cơ thể.",
        slug: "tra-gung-mat-ong",
    },
    {
        id: 9,
        name: "Trà Cúc La Mã",
        price: 90000,
        old_price: 105000,
        discount: "Giảm 14%",
        rating: "★★★★☆ (65+ đánh giá)",
        weight: "150g",
        packaging: "Hũ nhựa an toàn",
        origin: "Lào Cai",
        image: imageProduct1,
        description:
            "Trà hoa cúc tự nhiên giúp giảm căng thẳng, cải thiện giấc ngủ, vị dịu nhẹ và thư giãn.",
        slug: "tra-cuc-la-ma",
    },
    {
        id: 10,
        name: "Trà Atiso Đà Lạt",
        price: 85000,
        old_price: 100000,
        discount: "Giảm 15%",
        rating: "★★★★☆ (75+ đánh giá)",
        weight: "250g",
        packaging: "Túi lọc tiện lợi",
        origin: "Đà Lạt",
        image: imageProduct1,
        description:
            "Trà Atiso mát gan, thanh lọc cơ thể, vị ngọt nhẹ tự nhiên, phù hợp uống hàng ngày.",
        slug: "tra-atiso-da-lat",
    },
];
